# -*- coding: utf-8 -*-
"""Museum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eq3Md5Rn6Y9uAPGSl5zZ-n8-ycr-99dC
"""

import streamlit as st
import requests
import pandas as pd

# 페이지 설정
st.set_page_config(page_title="Open Museum API", page_icon="🖼️", layout="centered")

st.title("🖼️ Museum Artworks Open API")
st.caption("공개 예술 작품 데이터를 불러와 시각화합니다. (API 키 필요 없음)")

# 🔹 샘플 API (Harvard Art Museums Open Access Endpoint)
# 실제로는 교수님 교안에 있는 streamlit 앱처럼 JSON 데이터를 불러옴
url = "https://api.harvardartmuseums.org/object?size=5&apikey=DEMO_API_KEY"

if st.button("작품 불러오기"):
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()

        records = data.get("records", [])
        if len(records) == 0:
            st.warning("작품 데이터를 불러오지 못했습니다.")
        else:
            st.success(f"✅ 총 {len(records)}개의 작품 정보를 불러왔습니다.")

            # 표로 정리
            df = pd.DataFrame([
                {
                    "작품명": r.get("title", "N/A"),
                    "작가": r.get("people", [{}])[0].get("name", "Unknown") if r.get("people") else "Unknown",
                    "제작연도": r.get("dated", "N/A"),
                    "문화권": r.get("culture", "N/A"),
                    "이미지": r.get("primaryimageurl", None)
                }
                for r in records
            ])

            # 데이터 표시
            st.dataframe(df[["작품명", "작가", "제작연도", "문화권"]])

            # 이미지 보여주기
            st.subheader("🎨 작품 이미지 미리보기")
            for idx, row in df.iterrows():
                if row["이미지"]:
                    st.image(row["이미지"], caption=row["작품명"])
                else:
                    st.text(f"{row['작품명']} — (이미지 없음)")
    else:
        st.error(f"❌ 요청 실패: {response.status_code}")