# -*- coding: utf-8 -*-
"""Museum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eq3Md5Rn6Y9uAPGSl5zZ-n8-ycr-99dC
"""

import streamlit as st
import pandas as pd
import requests

st.set_page_config(page_title="국립중앙박물관 유물 오픈데이터", page_icon="🏺", layout="centered")

st.title("🏺 국립중앙박물관 오픈데이터")
st.caption("공공 데이터 기반 유물 정보 시각화 (API 키 불필요)")

# ✅ 예시용 공개 JSON 데이터 (국립중앙박물관 소장품 데이터셋)
url = "https://raw.githubusercontent.com/statickidz/NMK-museum-openapi/main/sample_data.json"

if st.button("유물 불러오기"):
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()

        # JSON을 DataFrame으로 변환
        df = pd.DataFrame(data)

        # 데이터 확인
        st.success(f"✅ {len(df)}개의 유물 정보를 불러왔습니다.")
        st.dataframe(df[["title_ko", "era", "material", "museum"]])

        st.subheader("🎨