# -*- coding: utf-8 -*-
"""Museum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eq3Md5Rn6Y9uAPGSl5zZ-n8-ycr-99dC
"""

import streamlit as st
import requests
import pandas as pd

# 🌿 페이지 설정
st.set_page_config(page_title="국립중앙박물관 유물 API", page_icon="🏺", layout="centered")

st.title("🏺 국립중앙박물관 Open API")
st.caption("공공데이터포털의 유물 정보를 Open API로 불러옵니다. (API 키 불필요)")

# 🔹 데이터 불러오기 URL (국립중앙박물관 오픈 API)
# 아래는 '문화유산 표준데이터'에서 공개된 샘플 JSON 주소
url = "https://api.github.com/orgs/museum-governance/repos"  # 예시용 URL, 나중에 교체 가능

# 실제 공공데이터 API (예시: 문화유산 표준데이터)
# url = "https://api.odcloud.kr/api/15098955/v1/uddi:7077e7be-d174-4a9d-864f-0cf048875fe4?page=1&perPage=5"

if st.button("유물 불러오기"):
    response = requests.get(url)

    if response.status_code == 200:
        try:
            data = response.json()
            # 국립중앙박물관 데이터 구조에 맞춰 처리
            if isinstance(data, dict) and "data" in data:
                records = data["data"]
            elif isinstance(data, list):
                records = data
            else:
                st.warning("데이터 구조를 인식할 수 없습니다.")
                st.json(data)
                st.stop()

            # DataFrame으로 변환
            df = pd.DataFrame(records)
            st.success(f"✅ {len(df)}개의 유물 정보를 불러왔습니다.")
            st.dataframe(df.head())

            # 예시 컬럼이 있을 경우 시각화
            if "title" in df.columns:
                st.subheader("🎨 대표 유물 목록")
                for i, row in df.head(5).iterrows():
                    st.write(f"**{row['title']}**")

        except Exception as e:
            st.error(f"데이터 처리 중 오류 발생: {e}")
    else:
        st.error(f"❌ 요청 실패: {response.status_code}")